# Generated by Django 4.2 on 2023-04-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='customer',
            new_name='policy_name',
        ),
        migrations.AlterField(
            model_name='question',
            name='admin_comment',
            field=models.CharField(default='Děkujeme za váš dotaz', max_length=200),
        ),
    ]
