# Generated by Django 4.2 on 2023-04-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0002_rename_customer_policy_policy_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='admin_comment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
